version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: pase_lista
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pase-lista
    volumes:
      - db-sql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin  
    ports:
      - "80:80"  
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"    
    depends_on:
      - postgres

volumes:
    db-sql: